### ISSUE TITLE
The processor keeps producing this error.

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#154]
The processor keeps producing this error.

```
Error processing '/gitea-data/git/repositories/sally/diy_particle_detector.git': Error: Command failed: cd '/data/checkout/sally/diy_particle_detector' && git rev-parse HEAD
processor_1  | fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
processor_1  | Use '--' to separate paths from revisions, like this:
processor_1  | 'git <command> [<revision>...] -- [<file>...]'
processor_1  | 
processor_1  |     at ChildProcess.exithandler (child_process.js:319:12)
processor_1  |     at ChildProcess.emit (events.js:375:28)
processor_1  |     at maybeClose (internal/child_process.js:1055:16)
processor_1  |     at Socket.<anonymous> (internal/child_process.js:441:11)
processor_1  |     at Socket.emit (events.js:375:28)
processor_1  |     at Pipe.<anonymous> (net.js:675:12) {
processor_1  |   killed: false,
processor_1  |   code: 128,
processor_1  |   signal: null,
processor_1  |   cmd: "cd '/data/checkout/sally/diy_particle_detector' && git rev-parse HEAD",
processor_1  |   stdout: 'HEAD\n',
processor_1  |   stderr: "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.\n" +
processor_1  |     "Use '--' to separate paths from revisions, like this:\n" +
processor_1  |     "'git <command> [<revision>...] -- [<file>...]'\n"
processor_1  | }
```

_Originally posted by @AbdulrhmnGhanem in https://github.com/kitspace/kitspace-v2/issues/100#issuecomment-880056684_

**Comment by kasbah** [comment]
I'm an idiot. Duplicate of #100
