### ISSUE TITLE
Processor on staging is crashing on lora32_node

### ISSUE THREAD

**Issue by kasbah** [kitspace/kitspace-v2#439]
```
2022-10-03T12:13:43.559208489Z meilisearch: adding/updating document id='4' for repo kaspar/watercontrol-pcb
2022-10-03T12:13:44.776780282Z failed kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/layout.svg Command failed: /app/dist/src/tasks/processKicadPCB/plot_kicad_pcb gerber /data/checkout/kaspar/lora32_node/Gerber/Heltec_Node.kicad_pcb /tmp/kitspace/data/files/kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/gerbers
2022-10-03T12:13:44.776839896Z Segmentation fault (core dumped)
2022-10-03T12:13:44.776847232Z 
2022-10-03T12:13:44.777253788Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/LoRa32_Node-39d4bda-gerbers.zip
2022-10-03T12:13:44.777385868Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/bottom.svg
2022-10-03T12:13:44.777536443Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/gerber-info.json
2022-10-03T12:13:44.777706785Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top.svg
2022-10-03T12:13:44.777799208Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top.png
2022-10-03T12:13:44.777881573Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top-large.png
2022-10-03T12:13:44.777898538Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top-meta.png
2022-10-03T12:13:44.777988031Z in_progress kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top-with-background.png
2022-10-03T12:13:44.780026306Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/LoRa32_Node-39d4bda-gerbers.zip
2022-10-03T12:13:44.780307623Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/bottom.svg
2022-10-03T12:13:44.780558141Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/gerber-info.json
2022-10-03T12:13:44.780796416Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top.svg
2022-10-03T12:13:44.781031784Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top.png
2022-10-03T12:13:44.781270003Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top-large.png
2022-10-03T12:13:44.781506486Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top-meta.png
2022-10-03T12:13:44.781716898Z done kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d/images/top-with-background.png
2022-10-03T12:13:44.782756712Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/layout.svg
2022-10-03T12:13:44.784195623Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/layout.svg
2022-10-03T12:13:44.784435541Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/d20-control-panel-2x1-f11d5a9-gerbers.zip
2022-10-03T12:13:44.784662074Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/bottom.svg
2022-10-03T12:13:44.784866189Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/gerber-info.json
2022-10-03T12:13:44.785059281Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top.svg
2022-10-03T12:13:44.785281750Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top.png
2022-10-03T12:13:44.785493795Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top-large.png
2022-10-03T12:13:44.785680704Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top-meta.png
2022-10-03T12:13:44.785866728Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top-with-background.png
2022-10-03T12:13:44.787576365Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/d20-control-panel-2x1-f11d5a9-gerbers.zip
2022-10-03T12:13:44.787808153Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/bottom.svg
2022-10-03T12:13:44.788016309Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/gerber-info.json
2022-10-03T12:13:44.788389107Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top.svg
2022-10-03T12:13:44.788418520Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top.png
2022-10-03T12:13:44.788471022Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top-large.png
2022-10-03T12:13:44.788487510Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top-meta.png
2022-10-03T12:13:44.788527699Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-control-panel-2x1/images/top-with-background.png
2022-10-03T12:13:44.789259661Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/layout.svg
2022-10-03T12:13:44.790516270Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/layout.svg
2022-10-03T12:13:44.790965698Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/d20-tri-f11d5a9-gerbers.zip
2022-10-03T12:13:44.791187102Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/bottom.svg
2022-10-03T12:13:44.791388396Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/gerber-info.json
2022-10-03T12:13:44.791593312Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top.svg
2022-10-03T12:13:44.791803850Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top.png
2022-10-03T12:13:44.792004362Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top-large.png
2022-10-03T12:13:44.792227005Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top-meta.png
2022-10-03T12:13:44.792422797Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top-with-background.png
2022-10-03T12:13:44.794008470Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/d20-tri-f11d5a9-gerbers.zip
2022-10-03T12:13:44.794040327Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/bottom.svg
2022-10-03T12:13:44.794297201Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/gerber-info.json
2022-10-03T12:13:44.794323931Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top.svg
2022-10-03T12:13:44.794555499Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top.png
2022-10-03T12:13:44.794742898Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top-large.png
2022-10-03T12:13:44.794939187Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top-meta.png
2022-10-03T12:13:44.794964601Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri/images/top-with-background.png
2022-10-03T12:13:44.795758979Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/layout.svg
2022-10-03T12:13:44.797156677Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/layout.svg
2022-10-03T12:13:44.797381778Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/d20-tri-panel-4x1-f11d5a9-gerbers.zip
2022-10-03T12:13:44.797613145Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/bottom.svg
2022-10-03T12:13:44.797822267Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/gerber-info.json
2022-10-03T12:13:44.798072634Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top.svg
2022-10-03T12:13:44.798305989Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top.png
2022-10-03T12:13:44.798555664Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top-large.png
2022-10-03T12:13:44.798787168Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top-meta.png
2022-10-03T12:13:44.799008090Z in_progress kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top-with-background.png
2022-10-03T12:13:44.800653920Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/d20-tri-panel-4x1-f11d5a9-gerbers.zip
2022-10-03T12:13:44.800704069Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/bottom.svg
2022-10-03T12:13:44.800988235Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/gerber-info.json
2022-10-03T12:13:44.801029330Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top.svg
2022-10-03T12:13:44.801309455Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top.png
2022-10-03T12:13:44.801336132Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top-large.png
2022-10-03T12:13:44.801572362Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top-meta.png
2022-10-03T12:13:44.801782595Z done kaspar/d20-hardware/f11d5a92aa09db1370572ac9001f02feb15e1096/d20-tri-panel-4x1/images/top-with-background.png
2022-10-03T12:13:44.802480278Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/layout.svg
2022-10-03T12:13:44.804160895Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/layout.svg
2022-10-03T12:13:44.804437325Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/ulx3s-57fb182-gerbers.zip
2022-10-03T12:13:44.804700905Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/bottom.svg
2022-10-03T12:13:44.804945804Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/gerber-info.json
2022-10-03T12:13:44.805209852Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top.svg
2022-10-03T12:13:44.805448962Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top.png
2022-10-03T12:13:44.805679454Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top-large.png
2022-10-03T12:13:44.805849311Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top-meta.png
2022-10-03T12:13:44.806021514Z in_progress kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top-with-background.png
2022-10-03T12:13:44.808869818Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/ulx3s-57fb182-gerbers.zip
2022-10-03T12:13:44.809029525Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/bottom.svg
2022-10-03T12:13:44.809176330Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/gerber-info.json
2022-10-03T12:13:44.809431860Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top.svg
2022-10-03T12:13:44.809587847Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top.png
2022-10-03T12:13:44.809734065Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top-large.png
2022-10-03T12:13:44.809979146Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top-meta.png
2022-10-03T12:13:44.810226120Z done kaspar/ulx3s/57fb182f80e75436b139d961ac778d4906591ab8/images/top-with-background.png
2022-10-03T12:13:44.811119817Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/layout.svg
2022-10-03T12:13:44.812756950Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/layout.svg
2022-10-03T12:13:44.812916955Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/watercontrol-pcb-e3224e1-gerbers.zip
2022-10-03T12:13:44.813086105Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/bottom.svg
2022-10-03T12:13:44.813334839Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/gerber-info.json
2022-10-03T12:13:44.813474994Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top.svg
2022-10-03T12:13:44.813627508Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top.png
2022-10-03T12:13:44.813948872Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top-large.png
2022-10-03T12:13:44.814189111Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top-meta.png
2022-10-03T12:13:44.814330526Z in_progress kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top-with-background.png
2022-10-03T12:13:44.816476528Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/watercontrol-pcb-e3224e1-gerbers.zip
2022-10-03T12:13:44.816557157Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/bottom.svg
2022-10-03T12:13:44.816593400Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/gerber-info.json
2022-10-03T12:13:44.816600613Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top.svg
2022-10-03T12:13:44.816605833Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top.png
2022-10-03T12:13:44.816806361Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top-large.png
2022-10-03T12:13:44.816819303Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top-meta.png
2022-10-03T12:13:44.817019214Z done kaspar/watercontrol-pcb/e3224e1b6f020ceb14d60237280f60763b54aa95/images/top-with-background.png
2022-10-03T12:13:45.040864560Z Error: Missing key for job /data/files/kaspar/lora32_node/39d4bdac7fe4fa08bc62be12099fee765231813d. updateProgress
2022-10-03T12:13:45.040903389Z     at Function.finishedErrors (/app/node_modules/bullmq/dist/cjs/classes/scripts.js:182:24)
2022-10-03T12:13:45.040911252Z     at Function.updateProgress (/app/node_modules/bullmq/dist/cjs/classes/scripts.js:123:24)
2022-10-03T12:13:45.040916536Z     at runMicrotasks (<anonymous>)
2022-10-03T12:13:45.040922015Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kasbah** [comment]
Old issue, lora32_node is working at the moment.
